### PR TITLE
Fix version compatibility

### PR DESCRIPTION
**Pull request by tsufurukawa**
These changes make this extension compatible with all newer versions of Solidus. The tests are all passing now as well!!

### CODE REVIEW

**Comment by fastjames** [comment]
FWIW these are almost exactly the same changes we made to achieve 2.3+ compatibility in our local branch. I would love to see this get merged.

**Comment by octave** [comment]
👍

**Comment by dhonig** [comment]
Thanks for the contributions.  I've tagged @acreilly and @kinduff  to review these.  We should be able to get them merged in without too much further delay.

**Comment by kinduff** [comment]
Looks good to me! Thanks for the contribution! :panda_face:

**Comment by tsufurukawa** [comment]
@kinduff Just squashed those commits! Lemme know if you need me to do anything else!

**Comment by kinduff** [comment]
@tsufurukawa Thank you! Don't hesitate to propose any further changes that could improve this gem.

**Pull request merged**
